language: ruby
rvm: 2.7.0
sudo: false
cache: bundler
bundler_args: --without production
env:
  global:
    - CC_TEST_REPORTER_ID=ee5f1ddfb29308a4c0627071b2f6f6bbb0cfdbb36a3229c12bd108dcf2e6c222
    - CCTR=/tmp/cc-test-reporter
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > $CCTR
  - chmod +x $CCTR
  - $CCTR before-build
script:
  - bundle exec rake db:setup
  - bundle exec rake spec
#   - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json
  - bundle exec rake cucumber
#   - $CCTR format-coverage --output coverage/codeclimate.$SUITE.json
after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/backend/.resultset.json # Format backend coverage
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json coverage/frontend/lcov.info  # Format frontend coverage
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2                  # Sum both coverage parts into coverage/codeclimate.json
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi  # Upload coverage/codeclimate.json
#   - $CCTR sum-coverage coverage/codeclimate.*.json | $CCTR upload-coverage
#   - $CCTR after-build --exit-code $TRAVIS_TEST_RESULT
